---
- hosts: web
  tasks:
      - name: Create file
        become: yes
        file:
            path: /etc/motd
            state: touch
      - name: return motd to registered var
        command: cat /etc/motd
        register: mymotd 
